# Generated by Django 3.2.3 on 2021-06-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT VALUE', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('brands', models.CharField(max_length=400)),
                ('nutriscore_grade', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('stores', models.CharField(max_length=400, null=True)),
                ('category', models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.PROTECT, to='mes_aliments.category')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='mes_aliments.product')),
                ('substitute', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='substitute', to='mes_aliments.product')),
            ],
        ),
    ]
