# Generated by Django 3.2.3 on 2021-06-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes_aliments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('brands', models.CharField(max_length=200)),
                ('nutriscore_grade', models.CharField(max_length=1)),
                ('url', models.URLField()),
                ('stores', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mes_aliments.category')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='mes_aliments.product')),
                ('substitute', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='substitute', to='mes_aliments.product')),
            ],
        ),
    ]
